import type { Project } from "../types";

export const sampleProjects: Project[] = [
  {
    id: "project-1",
    customer: "Northstar Health",
    name: "Clinical workflow rollout",
    product: "Managed Ethernet · 1 Gbps",
    site: "Leeds, LS1 3EX",
    owner: "Maya Chen",
    salesOwner: "Alex Morgan",
    thirdParty: "ChannelLink",
    supplier: "Openreach",
    crfReference: "CRF-001",
    thirdPartyReference: "CL-001",
    supplierReference: "OR-001",
    status: "On track",
    priority: "High",
    progress: 75,
    currentStage: "delivery",
    dueDate: "2026-08-21",
    openRisks: 0,
    blockers: [],
    monthlyValue: 18400,
    updatedAt: "2026-07-26T14:20:00.000Z",
  },
  {
    id: "project-2",
    customer: "Veridian Bank",
    name: "Enterprise data migration",
    product: "DIA and managed firewall",
    site: "Birmingham, B1 1TT",
    owner: "Theo Grant",
    salesOwner: "Priya Shah",
    thirdParty: "ChannelLink",
    supplier: "Virgin Media Business",
    crfReference: "CRF-002",
    thirdPartyReference: "CL-002",
    supplierReference: "VMB-002",
    status: "At risk",
    priority: "Critical",
    progress: 63,
    currentStage: "survey-design",
    dueDate: "2026-08-06",
    openRisks: 1,
    blockers: [
      {
        id: "blocker-1",
        type: "ECC",
        summary: "Construction charges awaiting approval.",
        status: "Open",
        accountableParty: "Customer",
        resolverRole: "MSP Commercial owner",
        nextAction: "Validate charges and obtain customer approval.",
        targetDate: "2026-07-30",
      },
    ],
    monthlyValue: 32750,
    updatedAt: "2026-07-27T09:15:00.000Z",
  },
  {
    id: "project-3",
    customer: "CivicWorks",
    name: "Resident portal adoption",
    product: "Cloud contact centre",
    site: "Manchester, M2 5DB",
    owner: "Maya Chen",
    salesOwner: "Louise Ward",
    thirdParty: "CloudSource",
    supplier: "Genesys",
    crfReference: "CRF-003",
    thirdPartyReference: "CS-003",
    supplierReference: "GEN-003",
    status: "Complete",
    priority: "Low",
    progress: 100,
    currentStage: "handover",
    dueDate: "2026-07-18",
    openRisks: 0,
    blockers: [],
    monthlyValue: 9800,
    updatedAt: "2026-07-18T17:00:00.000Z",
  },
];
